server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  profiles:
    active: dev

props:
  steamProviderUrl: http://steamcommunity.com/openid
  steamApiKey: 4BB7EB42707E3B08E291523E2FB84BF2 # registered for localhost