spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/cookUp
    username: cookUp
    password: cookUpPass

  thymeleaf:
    cache: false