spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiziCaseDb
    username: hiziCase
    password: hiziCasePass
    driver-class: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update # TODO change and update prod db using migration scripts only (liquidbase?)
