server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/cookUp
    username: cookUp
    password: cookUpPass
    driver-class: org.postgresql.Driver

  data:
    rest:
      base-path: /api

  thymeleaf:
    mode: LEGACYHTML5
    cache: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

  profiles:
    active: dev
